import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";

const inter = Poppins({ subsets: ["latin"] , weight : '700' });

export const metadata = {
  title: "Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
